// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcwaiiveciffdrgwelph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjd2FpaXZlY2lmZmRyZ3dlbHBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NTI4ODUsImV4cCI6MjA2NzAyODg4NX0.KJORq7J6Lih2R4a0Q8UBTQisifDH3H3SsfyGofuvdL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});